export enum SystemEventType {
    OneSecond = 0,
    FourSeconds = 1,
    SixHertz = 2,
    AircraftLoaded = 3,
    Crashed = 4,
    CrashReset = 5,
    FlightLoaded = 6,
    FlightSaved = 7,
    FlightPlanActivated = 8,
    FlightPlanDeactivated = 9,
    Frame = 10,
    ObjectAdded = 11,
    ObjectRemoved = 12,
    Pause = 13,
    PauseEX1 = 14,
    Paused = 15,
    PauseFrame = 16,
    PositionChanged = 17,
    Sim = 18,
    SimStart = 19,
    SimStop = 20,
    Sound = 21,
    Unpaused = 22,
    View = 23,
}
